# Generated by Django 5.0.7 on 2024-10-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_tagged_users_like_comment_post_tagged_users_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
