# Generated by Django 4.2.16 on 2024-10-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name_plural": "Chats"},
        ),
    ]
